### ISSUE TITLE
Plugin cannot connect

### ISSUE THREAD

**Issue by liujvnes** [zombieyang/sd-ppp#2]
![image](https://github.com/zombieyang/sd-ppp/assets/25132014/ea389852-b4e3-471c-9b26-7cd2d76b1254)
No response when clicking connect

**Comment by zombieyang** [comment]
Did your comfyUI run in 127.0.0.1:8188 correctly?

**Comment by liujvnes** [comment]
> Did your comfyUI run in 127.0.0.1:8188 correctly?

comfyui runs normally and the port is correct. https://github.com/Acly/krita-ai-diffusion in krita can support connection. In addition, the krita-ai-diffusion plug-in function is set and the interactive experience is very good, especially ControlNet and Live function, I hope similar functions can be developed, thank you very much!

**Comment by liujvnes** [comment]
> > Did your comfyUI run in 127.0.0.1:8188 correctly?
> 
> comfyui runs normally and the port is correct. https://github.com/Acly/krita-ai-diffusion in krita can support connection. In addition, the krita-ai-diffusion plug-in function is set and the interactive experience is very good, especially ControlNet and Live function, I hope similar functions can be developed, thank you very much!

![屏幕截图 2024-04-14 174525](https://github.com/zombieyang/sd-ppp/assets/25132014/f531b611-0635-4029-881e-fbad2230d2d5)

**Comment by Dog-brother0113** [comment]
> > 你的 comfyUI 在 127.0.0.1:8188 正确运行吗？
> 
> comfyui运行正常，端口正确。 krita中的https://github.com/Acly/krita-ai-diffusion可以支持连接。另外，设置了krita-ai-diffusion插件功能，交互体验非常好，特别是ControlNet和Live功能，希望能开发出类似的功能，非常感谢！

The author's plugin sends images directly from PS to comfyui, and after running in comfyui, it directly sends them to PS. In comfyui, you can add nodes as you like.
【作者的插件是把图片直接从ps发送到comfyui中，在comfyui中跑完图直接发送到ps中，在comfyui中你可以随便加节点这样。】

**Comment by tianlang0704** [comment]
Empty input box cauese this bug (the grayed-out text in the box is placeholder text and the actual text box is empty).
And the empty text box causes error so later inputs are unusable before restart of PS, and once it successfully connects, the plugin remembers the correct address so people who successfully connected once won't encounter this.

There's a workaround for this bug before the fix is merged.
all you need to do is restart PS, and type out the ComfyUI address THE FIRST TRY, which if you encountered this bug, it's probably http://127.0.0.1:8188.
if it didn't connect the first time, you probably need to restart PS to try the second time.

**Comment by zombieyang** [comment]
merge the fix in 0.0.2
