### ISSUE TITLE
[Feature Request] Get RGB and selection alpha output from one node

### ISSUE THREAD

**Issue by Jonseed** [zombieyang/sd-ppp#52]
It would be nice if you could get the RGB output and selection (lasso) alpha output from a single node. Currently you can only get one or the other, but not both (unless you only get the RGB inside the selection). If you allowed the true `alpha channel` output, then you could convert a selection to alpha channel in Photoshop, and output both? For example:

![Screenshot 2024-11-05 090855](https://github.com/user-attachments/assets/a4a951e1-da68-4f5a-a6ed-36d33137d588)

But I currently don't like the ComfyUI-Photoshop method, because it outputs a compressed JPG from Photoshop which changes colors and introduces artifacts. So I prefer SD-PPP, which outputs perfect RGB from Photoshop!

**Comment by zombieyang** [comment]
I think coupling the selection and get image in the past version is bad idea, because `selection` is something in document level, it must have many issue in the future. In my experience, I found that if I use `Get Image from PS` + `selection_only` to get the MASK, It will break when the layer itself contains lots of transparent area I have no idea how to solve it.

So, what I plan to do in next version is to provide a node named `Get Selection from Photoshop`. If someone need to get the selected RGB, The comfy builtin `Join Image with Alpha` will help.

**Comment by zombieyang** [comment]
Done in 1.5.0
